function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_victor
	global.__objectDepths[1] = -999; // obj_carro_atropelador
	global.__objectDepths[2] = -999; // obj_carro_do_julio
	global.__objectDepths[3] = 0; // obj_spawner_de_julio
	global.__objectDepths[4] = 0; // obj_spawner_de_carro
	global.__objectDepths[5] = 9999; // obj_sangue
	global.__objectDepths[6] = -99999; // obj_poeira
	global.__objectDepths[7] = 9999999; // obj_poeira2
	global.__objectDepths[8] = -999999999; // obj_vermelhao_na_tela
	global.__objectDepths[9] = -999999999; // obj_fimdalinha
	global.__objectDepths[10] = 0; // obj_chapei
	global.__objectDepths[11] = 0; // obj_isaac
	global.__objectDepths[12] = 0; // obj_galinha
	global.__objectDepths[13] = 0; // obj_galinha_preta
	global.__objectDepths[14] = 0; // obj_pulo
	global.__objectDepths[15] = 0; // obj_parar_pulo
	global.__objectDepths[16] = 0; // obj_pulo_para_direita
	global.__objectDepths[17] = 0; // obj_pulo_para_baixo
	global.__objectDepths[18] = 0; // obj_pulo_para_esquerda
	global.__objectDepths[19] = 0; // obj_pulo_para_cima
	global.__objectDepths[20] = -999999; // obj_botao_cima
	global.__objectDepths[21] = -999999; // obj_botao_baixo
	global.__objectDepths[22] = -999999; // obj_botao_esquerda
	global.__objectDepths[23] = -999999; // obj_botao_direita
	global.__objectDepths[24] = -11; // obj_text_universal_parent
	global.__objectDepths[25] = -11; // obj_text_1
	global.__objectDepths[26] = 0; // obj_balcao1
	global.__objectDepths[27] = 0; // obj_balcao2
	global.__objectDepths[28] = 0; // obj_mulher_parede
	global.__objectDepths[29] = 999999; // obj_mulher_tapet
	global.__objectDepths[30] = 0; // obj_mulher_porta
	global.__objectDepths[31] = 0; // obj_mulher_tv
	global.__objectDepths[32] = 0; // obj_wall
	global.__objectDepths[33] = 0; // obj_arvoreB
	global.__objectDepths[34] = 0; // obj_arvoreD
	global.__objectDepths[35] = 0; // obj_arvoreC
	global.__objectDepths[36] = 0; // obj_arvoreE
	global.__objectDepths[37] = 0; // obj_arvoreF
	global.__objectDepths[38] = 0; // obj_flor_azul
	global.__objectDepths[39] = 0; // obj_flor_roxa
	global.__objectDepths[40] = 0; // obj_flor_vermelha
	global.__objectDepths[41] = 0; // obj_pantaB
	global.__objectDepths[42] = 0; // obj_moita
	global.__objectDepths[43] = 0; // obj_pedra
	global.__objectDepths[44] = 0; // obj_planta
	global.__objectDepths[45] = 0; // obj_arvore
	global.__objectDepths[46] = 0; // obj_arvoreG
	global.__objectDepths[47] = 0; // obj_arvoreH
	global.__objectDepths[48] = 0; // obj_arvoreI
	global.__objectDepths[49] = 0; // obj_planta_no_vaso
	global.__objectDepths[50] = 0; // obj_vaso_de_flor
	global.__objectDepths[51] = 0; // obj_mata_atlantica
	global.__objectDepths[52] = 0; // obj_cenario
	global.__objectDepths[53] = 0; // obj_muro1
	global.__objectDepths[54] = 0; // obj_muro2
	global.__objectDepths[55] = 0; // obj_cadeira_roberto
	global.__objectDepths[56] = 0; // obj_videogame
	global.__objectDepths[57] = 0; // obj_play2
	global.__objectDepths[58] = 0; // obj_mesa_roberto
	global.__objectDepths[59] = 0; // obj_mesa_grande_roberto
	global.__objectDepths[60] = 0; // obj_pc_c_negocio
	global.__objectDepths[61] = 0; // obj_muro_terezinha_parente
	global.__objectDepths[62] = 0; // obj_muroB
	global.__objectDepths[63] = 0; // obj_caminhonete
	global.__objectDepths[64] = 0; // obj_muroB2
	global.__objectDepths[65] = 0; // obj_grade
	global.__objectDepths[66] = 0; // obj_grade_grande
	global.__objectDepths[67] = 0; // obj_grade_grande_vermelha
	global.__objectDepths[68] = 0; // obj_grade_vermelha
	global.__objectDepths[69] = 0; // obj_toco
	global.__objectDepths[70] = 0; // obj_portaozim
	global.__objectDepths[71] = 0; // obj_bancoo
	global.__objectDepths[72] = 0; // obj_placa
	global.__objectDepths[73] = 0; // obj_poste
	global.__objectDepths[74] = 0; // obj_portao_azul
	global.__objectDepths[75] = 0; // obj_parada
	global.__objectDepths[76] = 0; // obj_cercaV
	global.__objectDepths[77] = 0; // obj_cerca_H
	global.__objectDepths[78] = 0; // obj_UMA_cerca
	global.__objectDepths[79] = 0; // obj_placaX
	global.__objectDepths[80] = 0; // obj_placa_ao_contrario
	global.__objectDepths[81] = -999999; // obj_plaquinha_shop
	global.__objectDepths[82] = 0; // obj_jarro
	global.__objectDepths[83] = 0; // obj_bicicleta
	global.__objectDepths[84] = 0; // obj_bicicletas
	global.__objectDepths[85] = 0; // obj_cripta
	global.__objectDepths[86] = 0; // obj_apoiador_de_bike
	global.__objectDepths[87] = 0; // obj_mesa_com_cadeira
	global.__objectDepths[88] = 0; // obj_mesa
	global.__objectDepths[89] = 0; // obj_banco_branco
	global.__objectDepths[90] = 0; // obj_banco_branco_vertical
	global.__objectDepths[91] = 0; // obj_cerca_branca
	global.__objectDepths[92] = 0; // obj_cerca_brancaB
	global.__objectDepths[93] = 0; // obj_buraco
	global.__objectDepths[94] = 0; // obj_portao_vertical
	global.__objectDepths[95] = 0; // obj_barraca
	global.__objectDepths[96] = 0; // obj_mato
	global.__objectDepths[97] = 0; // obj_caixa_de_flor
	global.__objectDepths[98] = 0; // obj_banquim
	global.__objectDepths[99] = 0; // obj_cubo_nd_a_ver
	global.__objectDepths[100] = 0; // obj_mesa_c_coisa
	global.__objectDepths[101] = 0; // obj_correio_
	global.__objectDepths[102] = 0; // obj_carro
	global.__objectDepths[103] = 0; // obj_tetim
	global.__objectDepths[104] = 0; // obj_duas_caixas
	global.__objectDepths[105] = 0; // obj_placa_gym
	global.__objectDepths[106] = 0; // obj_portaoB
	global.__objectDepths[107] = 0; // obj_parede_do_portao
	global.__objectDepths[108] = 0; // obj_caixa_eletronico
	global.__objectDepths[109] = 0; // obj_super_bicicleta
	global.__objectDepths[110] = 0; // obj_sofa_vertical
	global.__objectDepths[111] = 0; // obj_cama_de_solteiro
	global.__objectDepths[112] = 0; // obj_cama_de_casal
	global.__objectDepths[113] = 0; // obj_pokebola
	global.__objectDepths[114] = 0; // obj_tronco_de_madeira
	global.__objectDepths[115] = 0; // obj_mesa_de_vasos
	global.__objectDepths[116] = 0; // obj_churrasqueira
	global.__objectDepths[117] = 0; // obj_cadeira_de_madeira
	global.__objectDepths[118] = 0; // obj_parede_vitao
	global.__objectDepths[119] = 0; // obj_porta_desbloqueavel
	global.__objectDepths[120] = 0; // portas
	global.__objectDepths[121] = -999999999; // obj_transicao_preta
	global.__objectDepths[122] = 0; // obj_setup
	global.__objectDepths[123] = 0; // obj_loja
	global.__objectDepths[124] = 0; // obj_botoes
	global.__objectDepths[125] = 0; // obj_itens
	global.__objectDepths[126] = 0; // obj_item_bolsa
	global.__objectDepths[127] = 0; // obj_item_bolsa2
	global.__objectDepths[128] = 0; // obj_item_pocao
	global.__objectDepths[129] = 0; // obj_item_Super_pocao
	global.__objectDepths[130] = 0; // obj_item_tistabola
	global.__objectDepths[131] = 0; // obj_item_Supertistabola
	global.__objectDepths[132] = 0; // obj_item_chave_da_mulher
	global.__objectDepths[133] = 0; // obj_item_tesoura
	global.__objectDepths[134] = 0; // obj_cartazFMA
	global.__objectDepths[135] = 0; // obj_cartazKAI


	global.__objectNames[0] = "obj_victor";
	global.__objectNames[1] = "obj_carro_atropelador";
	global.__objectNames[2] = "obj_carro_do_julio";
	global.__objectNames[3] = "obj_spawner_de_julio";
	global.__objectNames[4] = "obj_spawner_de_carro";
	global.__objectNames[5] = "obj_sangue";
	global.__objectNames[6] = "obj_poeira";
	global.__objectNames[7] = "obj_poeira2";
	global.__objectNames[8] = "obj_vermelhao_na_tela";
	global.__objectNames[9] = "obj_fimdalinha";
	global.__objectNames[10] = "obj_chapei";
	global.__objectNames[11] = "obj_isaac";
	global.__objectNames[12] = "obj_galinha";
	global.__objectNames[13] = "obj_galinha_preta";
	global.__objectNames[14] = "obj_pulo";
	global.__objectNames[15] = "obj_parar_pulo";
	global.__objectNames[16] = "obj_pulo_para_direita";
	global.__objectNames[17] = "obj_pulo_para_baixo";
	global.__objectNames[18] = "obj_pulo_para_esquerda";
	global.__objectNames[19] = "obj_pulo_para_cima";
	global.__objectNames[20] = "obj_botao_cima";
	global.__objectNames[21] = "obj_botao_baixo";
	global.__objectNames[22] = "obj_botao_esquerda";
	global.__objectNames[23] = "obj_botao_direita";
	global.__objectNames[24] = "obj_text_universal_parent";
	global.__objectNames[25] = "obj_text_1";
	global.__objectNames[26] = "obj_balcao1";
	global.__objectNames[27] = "obj_balcao2";
	global.__objectNames[28] = "obj_mulher_parede";
	global.__objectNames[29] = "obj_mulher_tapet";
	global.__objectNames[30] = "obj_mulher_porta";
	global.__objectNames[31] = "obj_mulher_tv";
	global.__objectNames[32] = "obj_wall";
	global.__objectNames[33] = "obj_arvoreB";
	global.__objectNames[34] = "obj_arvoreD";
	global.__objectNames[35] = "obj_arvoreC";
	global.__objectNames[36] = "obj_arvoreE";
	global.__objectNames[37] = "obj_arvoreF";
	global.__objectNames[38] = "obj_flor_azul";
	global.__objectNames[39] = "obj_flor_roxa";
	global.__objectNames[40] = "obj_flor_vermelha";
	global.__objectNames[41] = "obj_pantaB";
	global.__objectNames[42] = "obj_moita";
	global.__objectNames[43] = "obj_pedra";
	global.__objectNames[44] = "obj_planta";
	global.__objectNames[45] = "obj_arvore";
	global.__objectNames[46] = "obj_arvoreG";
	global.__objectNames[47] = "obj_arvoreH";
	global.__objectNames[48] = "obj_arvoreI";
	global.__objectNames[49] = "obj_planta_no_vaso";
	global.__objectNames[50] = "obj_vaso_de_flor";
	global.__objectNames[51] = "obj_mata_atlantica";
	global.__objectNames[52] = "obj_cenario";
	global.__objectNames[53] = "obj_muro1";
	global.__objectNames[54] = "obj_muro2";
	global.__objectNames[55] = "obj_cadeira_roberto";
	global.__objectNames[56] = "obj_videogame";
	global.__objectNames[57] = "obj_play2";
	global.__objectNames[58] = "obj_mesa_roberto";
	global.__objectNames[59] = "obj_mesa_grande_roberto";
	global.__objectNames[60] = "obj_pc_c_negocio";
	global.__objectNames[61] = "obj_muro_terezinha_parente";
	global.__objectNames[62] = "obj_muroB";
	global.__objectNames[63] = "obj_caminhonete";
	global.__objectNames[64] = "obj_muroB2";
	global.__objectNames[65] = "obj_grade";
	global.__objectNames[66] = "obj_grade_grande";
	global.__objectNames[67] = "obj_grade_grande_vermelha";
	global.__objectNames[68] = "obj_grade_vermelha";
	global.__objectNames[69] = "obj_toco";
	global.__objectNames[70] = "obj_portaozim";
	global.__objectNames[71] = "obj_bancoo";
	global.__objectNames[72] = "obj_placa";
	global.__objectNames[73] = "obj_poste";
	global.__objectNames[74] = "obj_portao_azul";
	global.__objectNames[75] = "obj_parada";
	global.__objectNames[76] = "obj_cercaV";
	global.__objectNames[77] = "obj_cerca_H";
	global.__objectNames[78] = "obj_UMA_cerca";
	global.__objectNames[79] = "obj_placaX";
	global.__objectNames[80] = "obj_placa_ao_contrario";
	global.__objectNames[81] = "obj_plaquinha_shop";
	global.__objectNames[82] = "obj_jarro";
	global.__objectNames[83] = "obj_bicicleta";
	global.__objectNames[84] = "obj_bicicletas";
	global.__objectNames[85] = "obj_cripta";
	global.__objectNames[86] = "obj_apoiador_de_bike";
	global.__objectNames[87] = "obj_mesa_com_cadeira";
	global.__objectNames[88] = "obj_mesa";
	global.__objectNames[89] = "obj_banco_branco";
	global.__objectNames[90] = "obj_banco_branco_vertical";
	global.__objectNames[91] = "obj_cerca_branca";
	global.__objectNames[92] = "obj_cerca_brancaB";
	global.__objectNames[93] = "obj_buraco";
	global.__objectNames[94] = "obj_portao_vertical";
	global.__objectNames[95] = "obj_barraca";
	global.__objectNames[96] = "obj_mato";
	global.__objectNames[97] = "obj_caixa_de_flor";
	global.__objectNames[98] = "obj_banquim";
	global.__objectNames[99] = "obj_cubo_nd_a_ver";
	global.__objectNames[100] = "obj_mesa_c_coisa";
	global.__objectNames[101] = "obj_correio_";
	global.__objectNames[102] = "obj_carro";
	global.__objectNames[103] = "obj_tetim";
	global.__objectNames[104] = "obj_duas_caixas";
	global.__objectNames[105] = "obj_placa_gym";
	global.__objectNames[106] = "obj_portaoB";
	global.__objectNames[107] = "obj_parede_do_portao";
	global.__objectNames[108] = "obj_caixa_eletronico";
	global.__objectNames[109] = "obj_super_bicicleta";
	global.__objectNames[110] = "obj_sofa_vertical";
	global.__objectNames[111] = "obj_cama_de_solteiro";
	global.__objectNames[112] = "obj_cama_de_casal";
	global.__objectNames[113] = "obj_pokebola";
	global.__objectNames[114] = "obj_tronco_de_madeira";
	global.__objectNames[115] = "obj_mesa_de_vasos";
	global.__objectNames[116] = "obj_churrasqueira";
	global.__objectNames[117] = "obj_cadeira_de_madeira";
	global.__objectNames[118] = "obj_parede_vitao";
	global.__objectNames[119] = "obj_porta_desbloqueavel";
	global.__objectNames[120] = "portas";
	global.__objectNames[121] = "obj_transicao_preta";
	global.__objectNames[122] = "obj_setup";
	global.__objectNames[123] = "obj_loja";
	global.__objectNames[124] = "obj_botoes";
	global.__objectNames[125] = "obj_itens";
	global.__objectNames[126] = "obj_item_bolsa";
	global.__objectNames[127] = "obj_item_bolsa2";
	global.__objectNames[128] = "obj_item_pocao";
	global.__objectNames[129] = "obj_item_Super_pocao";
	global.__objectNames[130] = "obj_item_tistabola";
	global.__objectNames[131] = "obj_item_Supertistabola";
	global.__objectNames[132] = "obj_item_chave_da_mulher";
	global.__objectNames[133] = "obj_item_tesoura";
	global.__objectNames[134] = "obj_cartazFMA";
	global.__objectNames[135] = "obj_cartazKAI";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
